import test from 'node:test';
import assert from 'node:assert/strict';
import {newCampaign,recruit,formArmy,activeArmy,selectArmy,transferUnit,nextDay,upkeep,setDestination,attachArmies,applyBattleResult,mergeArmy} from '../src/campaign.ts';
import {validSave} from '../src/storage.ts';
import {createBattle} from '../src/battle.ts';
function two(){const c=newCampaign();recruit(c,'rome');const city=c.cities.find(x=>x.id==='rome')!;assert.equal(formArmy(c,'rome',city.garrison.map(u=>u.id)),null);return c;}
test('formation takes selected garrison troops exactly once and keeps first army',()=>{const c=two();assert.equal(c.armies.length,2);assert.equal(c.armies[0].army.length,3);assert.equal(c.army.length,1);assert.equal(c.movement,0);assert.equal(c.cities[0].garrison.length,0);assert.ok(formArmy(c,'rome',['unknown']));});
test('army selection routes and movement are independent; all advance next day',()=>{const c=two(),second=activeArmy(c),first=c.armies[0];selectArmy(c,first.id);const before={...c.position};setDestination(c,c.cities.find(x=>x.id==='capua')!);assert.deepEqual(second.position,before);selectArmy(c,second.id);nextDay(c);assert.equal(second.movement,70);assert.notDeepEqual(first.position,before);assert.equal(c.activeArmyId,second.id);});
test('transfers preserve upkeep and cannot refresh movement; distance prevents transfer',()=>{const c=two(),second=activeArmy(c),first=c.armies[0],pay=upkeep(c);assert.equal(transferUnit(c,c.army[0].id,first.id),null);assert.equal(first.army.length,4);assert.equal(first.movement,0);assert.equal(second.army.length,0);assert.equal(upkeep(c),pay);selectArmy(c,first.id);second.position.x+=100;assert.ok(transferUnit(c,c.army[0].id,second.id));assert.equal(c.army.length,4);});
test('save roundtrip restores selected army accessors and separate troops',()=>{const c=two();const s=JSON.parse(JSON.stringify({schema:7,campaign:c,battle:null}));assert.ok(validSave(s));attachArmies(s.campaign);s.campaign.movement=12;assert.equal(s.campaign.armies[1].movement,12);selectArmy(s.campaign,s.campaign.armies[0].id);assert.equal(s.campaign.army.length,3);s.campaign.armies[1].army[0].men=NaN;assert.equal(validSave(s),false);});
test('battle result changes only the participating army',()=>{const c=two(),first=structuredClone(c.armies[0]);c.position={...c.enemyPosition};const b=createBattle(c.army,c.enemy);b.winner='boii';applyBattleResult(c,b,[],c.enemy);assert.deepEqual(c.armies[0],first);assert.equal(c.army.length,0);});

test('merging preserves troops and minimum movement and removes empty source',()=>{const c=two(),first=c.armies[0],pay=upkeep(c);assert.equal(mergeArmy(c,first.id),null);assert.equal(c.armies.length,1);assert.equal(c.army.length,4);assert.equal(c.movement,0);assert.equal(upkeep(c),pay);});
